/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './about.html',
    './categories.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#914d00",
        "primary-container": "#f28c28",
        "secondary": "#705d00",
        "secondary-container": "#fcd400",
        "tertiary": "#70585b",
        "tertiary-container": "#bb9ea1",
        "surface": "#fff8f4",
        "surface-variant": "#eae1db",
        "surface-container": "#f5ece6",
        "surface-container-low": "#fbf2ec",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#f0e6e0",
        "surface-container-highest": "#eae1db",
        "surface-dim": "#e1d8d3",
        "surface-bright": "#fff8f4",
        "background": "#fff8f4",
        "on-primary": "#ffffff",
        "on-primary-container": "#5d2f00",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6e5c00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#4a3538",
        "on-surface": "#1f1b17",
        "on-surface-variant": "#554336",
        "on-background": "#1f1b17",
        "outline": "#887364",
        "outline-variant": "#dbc2b0",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffe16d",
        "secondary-fixed-dim": "#e9c400",
        "on-secondary-fixed": "#221b00",
        "on-secondary-fixed-variant": "#544600",
        "tertiary-fixed": "#fbdbde",
        "tertiary-fixed-dim": "#debfc2",
        "on-tertiary-fixed": "#281719",
        "on-tertiary-fixed-variant": "#574144",
        "primary-fixed": "#ffdcc3",
        "primary-fixed-dim": "#ffb77d",
        "on-primary-fixed": "#2f1500",
        "on-primary-fixed-variant": "#6e3900",
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "none": "0",
        "DEFAULT": "0.25rem",
        "sm": "0.125rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "2rem",
        "3xl": "3rem",
        "full": "9999px",
      },
      screens: {
        "2xl": "1536px",
      },
    },
  },
  plugins: [],
};
