import express from 'express';
const router = express.Router();

const products = [
  { id: 101, name: 'Premium Magnetic Hand Whisk', category: 'home-kitchen', badge: 'Top Pick', shortBenefit: 'Elegantly balanced for effortless aerating.', keyBenefits: ['Balanced weight', 'Polished steel', 'Magnetic storage'], rating: '4.9/5 Recommended', image: '/assets/products/magnetic-whisk.png', price: 29.99 },
  { id: 102, name: 'Professional Rotating Whisk', category: 'home-kitchen', badge: 'Top Pick', shortBenefit: 'Semi-automatic rotation for perfect batters.', keyBenefits: ['Pressure-driven', 'Cordless design', 'Durable build'], rating: '4.8/5 Recommended', image: '/assets/products/rotating-whisk.png', price: 34.99 },
  { id: 103, name: 'Precision Balloon Whisk', category: 'home-kitchen', badge: 'Top Pick', shortBenefit: 'Refined design for aerating delicate sauces.', keyBenefits: ['Ultra-fine wire', 'Non-slip grip', 'Max efficiency'], rating: '4.7/5 Recommended', image: '/assets/products/balloon-whisk.png', price: 24.99 },
  { id: 104, name: 'Stainless Dough Whisk', category: 'home-kitchen', badge: 'Top Pick', shortBenefit: 'Ideal for thick bread doughs and heavy batters.', keyBenefits: ['Efficient loops', 'Heavy duty steel', 'Easy clean'], rating: '4.9/5 Recommended', image: '/assets/products/dough-whisk.png', price: 29.99 },
  { id: 105, name: 'Mini Dressings Whisk', category: 'home-kitchen', badge: 'Trending Now', shortBenefit: 'Compact precision for small batches.', keyBenefits: ['Space-saving', 'Fine control', 'Polished finish'], rating: '4.6/5 Highly Rated', image: '/assets/products/mini-whisk.png', price: 12.99 },
  { id: 106, name: 'Flat Roux Whisk', category: 'home-kitchen', badge: 'Trending Now', shortBenefit: 'Flat profile for seamless pan deglazing.', keyBenefits: ['Covers edges', 'Heat resistant', 'Prevents lumps'], rating: '4.8/5 Highly Rated', image: '/assets/products/flat-whisk.png', price: 19.99 },
  { id: 107, name: 'Coil Spring Whisk', category: 'home-kitchen', badge: 'Trending Now', shortBenefit: 'Vertical pumping action for fast frothing.', keyBenefits: ['Spring-loaded', 'Fast aeration', 'Compact storage'], rating: '4.7/5 Highly Rated', image: '/assets/products/coil-whisk.png', price: 15.99 },
  { id: 108, name: 'Silicone Tipped Whisk', category: 'home-kitchen', badge: 'Trending Now', shortBenefit: 'Gentle protection for non-stick cookware.', keyBenefits: ['Coated wires', 'Heat resistant', 'Dishwasher safe'], rating: '4.9/5 Highly Rated', image: '/assets/products/silicone-whisk.png', price: 22.99 },
  { id: 113, name: 'Bent Handle Saucier', category: 'home-kitchen', badge: 'Editor\'s Choice', shortBenefit: 'Ergonomic handle for low-fatigue slow stirring.', keyBenefits: ['Reduced wrist fatigue', 'Ideal for custards', 'Chef grade handle'], rating: '4.9/5 Premium Pick', image: '/assets/products/modern-kitchen-kettle-lifestyle.jpg', price: 24.99 },
  { id: 114, name: 'Silver Gooseneck Kettle', category: 'home-kitchen', badge: 'Editor\'s Choice', shortBenefit: 'Precision pour for artisan coffee bloom.', keyBenefits: ['Matte silver', 'Thermometer lid', 'Flow control'], rating: '4.8/5 Premium Pick', image: '/assets/products/matte-silver-gooseneck-kettle.jpg', price: 45.99 },
  { id: 115, name: 'Precision Black Kettle', category: 'home-kitchen', badge: 'Editor\'s Choice', shortBenefit: 'Sleek matte black for professional pour control.', keyBenefits: ['Black steel body', 'Rapid boil', 'Ergonomic grip'], rating: '4.9/5 Premium Pick', image: '/assets/products/matte-black-precision-kettle.jpg', price: 49.99 },
  { id: 116, name: 'Artisan Walnut Board', category: 'home-kitchen', badge: 'Editor\'s Choice', shortBenefit: 'Hand-crafted American Walnut surface.', keyBenefits: ['Solid wood', 'Beveled edges', 'Stays beautiful'], rating: '4.9/5 Premium Pick', image: '/assets/products/walnut-artisan-cutting-board.jpg', price: 65.00 },
  { id: 207, name: 'Sonic Toothbrush Pro', category: 'beauty-skincare', badge: 'Trending Now', shortBenefit: 'Professional cleaning with ultra-sonic technology.', keyBenefits: ['40,000 VPM', '4 modes', '8 brush heads'], rating: '4.8/5 Highly Rated', image: '/assets/products/sonic-toothbrush-premium.jpg', price: 34.99 },
  { id: 208, name: 'Sonic Facial Cleanser', category: 'beauty-skincare', badge: 'Top Pick', shortBenefit: 'Deeply cleanses for a radiant, healthy glow.', keyBenefits: ['Medical silicone', 'Waterproof', 'USB charging'], rating: '4.7/5 Highly Rated', image: '/assets/products/sonic-facial-cleansing-brush.jpg', price: 24.99 },
  { id: 211, name: 'Pure Hyaluronic Serum', category: 'beauty-skincare', badge: 'Editor\'s Choice', shortBenefit: 'Intense hydration for a youthful complexion.', keyBenefits: ['99% pure', 'Non-greasy', 'Natural botanicals'], rating: '4.9/5 Premium Pick', image: '/assets/products/hyaluronic-acid-serum-studio.jpg', price: 18.99 },
  { id: 212, name: 'Jade Roller & Gua Sha', category: 'beauty-skincare', badge: 'Trending Now', shortBenefit: 'Promote lymphatic drainage and facial contouring.', keyBenefits: ['Natural jade stone', 'Cooling effect', 'Contour set'], rating: '4.7/5 Highly Rated', image: '/assets/products/hyaluronic-serum-jade-roller-set.jpg', price: 15.99 },
  { id: 301, name: 'Wellness Tech Trio', category: 'health-personal-care', badge: 'Top Pick', shortBenefit: 'Integrated recovery tools for physical excellence.', keyBenefits: ['High-perf trio', 'Charging case', 'Feedback sensors'], rating: '4.8/5 Recommended', image: '/assets/products/wellness-tech-essentials-trio.jpg', price: 89.99 },
  { id: 302, name: 'Orthopedic Back Belt', category: 'health-personal-care', badge: 'Top Pick', shortBenefit: 'Adjustable support for improved alignment.', keyBenefits: ['Breathable mesh', 'Invisible under shirt', 'Adjustable fit'], rating: '4.7/5 Recommended', image: '/assets/products/orthopedic-back-support-belt.jpg', price: 19.99 },
  { id: 303, name: 'Massage Gun Pro Set', category: 'health-personal-care', badge: 'Top Pick', shortBenefit: 'Percussive therapy for deep muscle recovery.', keyBenefits: ['Quiet motor', 'Interchangeable heads', 'Long battery'], rating: '4.9/5 Recommended', image: '/assets/products/massage-gun-pro-attachments.jpg', price: 79.99 },
  { id: 305, name: 'Ash Wood Aroma Diffuser', category: 'health-personal-care', badge: 'Trending Now', shortBenefit: 'Transform any room into a calming spa.', keyBenefits: ['Natural ash wood', 'Ultrasonic mist', 'Auto-shutoff'], rating: '4.8/5 Highly Rated', image: '/assets/products/ash-wood-aroma-diffuser.jpg', price: 28.99 },
  { id: 307, name: 'Massage Gun Slate', category: 'health-personal-care', badge: 'Trending Now', shortBenefit: 'Premium slate percussive physical relief.', keyBenefits: ['Slate finish', 'Even weight', 'Quiet glide'], rating: '4.9/5 Highly Rated', image: '/assets/products/massage-gun-pro-slate.jpg', price: 65.99 },
  { id: 405, name: 'Pet Track Smart Collar', category: 'pet-supplies', badge: 'Top Pick', shortBenefit: 'Precision GPS and health tracking for pets.', keyBenefits: ['Real-time GPS', 'Health metrics', 'Durable strap'], rating: '4.5/5 Highly Rated', image: '/assets/products/pet-track-smart-collar.jpg', price: 14.99 },
  { id: 406, name: 'Pet Track Premium', category: 'pet-supplies', badge: 'Top Pick', shortBenefit: 'High-visibility tracking for active dogs.', keyBenefits: ['Reflective edges', 'Waterproof', 'Max range'], rating: '4.6/5 Highly Rated', image: '/assets/products/pet-track-premium-collar.jpg', price: 22.99 },
  { id: 501, name: 'Baby Safety Clipper', category: 'baby-products', badge: 'Top Pick', shortBenefit: 'Stress-free grooming with whisper-quiet tech.', keyBenefits: ['Night light', '6 safety heads', 'Adjustable spin'], rating: '4.9/5 Recommended', image: '/assets/products/baby-clipper-premium.png', price: 19.99 },
  { id: 502, name: 'Infant Bath Support', category: 'baby-products', badge: 'Top Pick', shortBenefit: 'Ergonomic, non-slip bath safety for newborns.', keyBenefits: ['Soft mesh', 'Quick dry', 'Fits any tub'], rating: '4.8/5 Recommended', image: '/assets/products/baby-bath-support.png', price: 26.99 },
  { id: 505, name: 'Muslin Swaddle Bundle', category: 'baby-products', badge: 'Trending Now', shortBenefit: 'Organic, breathable bamboo swaddle sets.', keyBenefits: ['Organic bamboo', 'Extra large size', 'Breathable weave'], rating: '4.7/5 Highly Rated', image: '/assets/products/baby-muslin-swaddle-bundle.jpg', price: 22.99 },
  { id: 606, name: 'Phone Dash Mount', category: 'electronics-accessories', badge: 'Trending Now', shortBenefit: 'Minimalist, secure magnetic docking for cars.', keyBenefits: ['Strong suction', 'Telescopic arm', 'Minimal profile'], rating: '4.8/5 Highly Rated', image: '/assets/products/magnetic-phone-mount.png', price: 18.99 },
  { id: 607, name: 'Carbon Fiber Charging Hub', category: 'electronics-accessories', badge: 'Top Pick', shortBenefit: 'Sleek carbon fiber multi-device station.', keyBenefits: ['15W charging', 'Anti-slip', 'Modern look'], rating: '4.8/5 Highly Rated', image: '/assets/products/carbon-fiber-charging-hub.jpg', price: 42.99 },
  { id: 610, name: '3-in-1 Charging Base', category: 'electronics-accessories', badge: 'Editor\'s Choice', shortBenefit: 'Hands-free charging for phone, watch, and pods.', keyBenefits: ['Full station', 'Adjustable angle', 'Weighted base'], rating: '4.8/5 Premium Pick', image: '/assets/products/3-in-1-charging-station.png', price: 44.99 },
  { id: 611, name: 'Leather Watch Band', category: 'electronics-accessories', badge: 'Trending Now', shortBenefit: 'Genuine leather band with signature stitching.', keyBenefits: ['Genuine leather', 'Polished buckles', 'Universal Series fit'], rating: '4.9/5 Premium Pick', image: '/assets/products/leather-watch-band.png', price: 35.00 },
  { id: 701, name: 'Elite Resistance Set', category: 'sports-fitness', badge: 'Top Pick', shortBenefit: 'Portable strength station for gym-quality results.', keyBenefits: ['Stackable tension', 'Snap-resistant', 'Portable kit'], rating: '4.8/5 Recommended', image: '/assets/products/resistance-band-set.png', price: 29.99 },
  { id: 703, name: 'Emerald TPE Yoga Mat', category: 'sports-fitness', badge: 'Top Pick', shortBenefit: 'Extra-thick cushioning with non-slip texture.', keyBenefits: ['Non-slip grip', 'Alignment lines', 'Eco-TPE build'], rating: '4.7/5 Recommended', image: '/assets/products/tpe-yoga-mat.png', price: 35.99 },
  { id: 706, name: 'Weighted Jump Rope', category: 'sports-fitness', badge: 'Trending Now', shortBenefit: 'High-speed rotation with ergonomic control.', keyBenefits: ['Steel wire cable', 'Ball bearings', 'Memory foam grips'], rating: '4.8/5 Highly Rated', image: '/assets/products/weighted-jump-rope.png', price: 12.99 },
  { id: 708, name: 'Pro Lumbar Lifting Belt', category: 'sports-fitness', badge: 'Editor\'s Choice', shortBenefit: 'Heavy-duty lumbar support for elite training.', keyBenefits: ['Double prong steel', 'High-density pad', 'Reduced strain'], rating: '4.8/5 Premium Pick', image: '/assets/products/pro-lifting-support-belt.jpg', price: 34.99 },
  { id: 801, name: 'Elite Sourcing Kit', category: 'global-trade', badge: 'Premium Service', shortBenefit: 'Luxury toolkit for global trade and sourcing events.', keyBenefits: ['Leather notebook', 'Premium pen set', 'Logistics access'], rating: '5.0/5 Top Choice', image: '/assets/products/elite-sourcing-kit.png', price: 199.00 }
];

const testimonials = [
  { id: 1, name: 'Michael T.', location: 'Texas, USA', quote: 'Superior Craftsmanship', text: 'Superior craftsmanship and world-class logistics. MRT International delivers excellence in every shipment.', region: 'us' },
  { id: 2, name: 'Jessica L.', location: 'California, USA', quote: 'Boutique Curation', text: 'The boutique catalog is curated with extreme care. Every product feels like a luxury item tailored for elite needs.', region: 'us' },
  { id: 3, name: 'David R.', location: 'New York, USA', quote: 'Reliable Global Trade', text: 'MRT has transformed our supply chain. Their products are not just items, they are assets for our business.', region: 'us' },
  { id: 4, name: 'Emma W.', location: 'London, UK', quote: 'High-Fidelity Service', text: 'Fast, secure, and incredibly professional. The social inquiry model makes elite sourcing feel personal.', region: 'us' },
  { id: 5, name: 'Ahmed K.', location: 'Abu Dhabi, UAE', quote: 'Professional Sourcing', text: 'Their Elite Sourcing Kit is a game changer for our trade delegations. Truly professional and localized excellence.', region: 'ae' },
  { id: 6, name: 'Sara M.', location: 'Dubai, UAE', quote: 'World-Class Delivery', text: 'Exceptional delivery speed to the UAE. The product quality exceeded our high standards for artisanal skincare.', region: 'ae' },
  { id: 7, name: 'Omar F.', location: 'Riyadh, SA', quote: 'Strategic Partnership', text: 'MRT is more than a supplier; they are a strategic partner in our luxury retail expansion.', region: 'ae' },
  { id: 8, name: 'Layla H.', location: 'Doha, Qatar', quote: 'Aesthetic Brilliance', text: 'The glassmorphism design mirrors the quality of their products. Clear, premium, and highly efficient.', region: 'ae' }
];

const categoryThemes = {
  'home-kitchen': { primary: '#914d00', secondary: '#f28c28', title: 'Modern Kitchen', subtitle: 'Culinary brilliance and lifestyle essentials', image: '/assets/categories/home-kitchen.png', seoTitle: 'Elite Best Home & Kitchen Collection (2026)', seoIntro: 'Curated selection of premium kitchenware and home essentials for the modern lifestyle.' },
  'beauty-skincare': { primary: '#701b2f', secondary: '#ffb2bd', title: 'Artisanal Beauty', subtitle: 'Pristine formulas for radiant maintenance', image: '/assets/categories/beauty-skincare.png', seoTitle: 'Premium Beauty & Skincare Essentials (2026)', seoIntro: 'Discover professional-grade skincare and beauty tools designed for lasting radiance.' },
  'health-personal-care': { primary: '#006a6a', secondary: '#00cfcf', title: 'Personal Vitality', subtitle: 'Advanced recovery and wellness curations', image: '/assets/categories/health-wellness.png', seoTitle: 'High-Performance Health & Wellness Gear (2026)', seoIntro: 'Advanced recovery tools and wellness essentials tailored for elite physical maintenance.' },
  'pet-supplies': { primary: '#3a6a00', secondary: '#8ce33a', title: 'Pet Curations', subtitle: 'Sophisticated gear for companions', image: '/assets/categories/pet-supplies.png', seoTitle: 'World-Class Pet Supplies & Tracking (2026)', seoIntro: 'Precision tracking and professional grooming gear for your loyal companions.' },
  'baby-products': { primary: '#004a77', secondary: '#7fbaff', title: 'Baby Essentials', subtitle: 'Nordic design for modern parents', image: '/assets/categories/baby-products.png', seoTitle: 'Safe & Sustainable Baby Essentials (2026)', seoIntro: 'Ergonimic designs and safety-first grooming tools for the next generation.' },
  'electronics-accessories': { primary: '#1f1b17', secondary: '#bf8f00', title: 'Tech Companions', subtitle: 'Performance-driven digital gear', image: '/assets/categories/electronics.png', seoTitle: 'Elite Tech Accessories & Charging Hubs (2026)', seoIntro: 'High-performance digital essentials and minimalist charging solutions for the tech-savvy professional.' },
  'sports-fitness': { primary: '#006e2a', secondary: '#55f985', title: 'Peak Performance', subtitle: 'Minimalist gear for elite training', image: '/assets/categories/sports-fitness.png', seoTitle: 'Professional-Grade Sports & Fitness Gear (2026)', seoIntro: 'Minimalist equipment and heavy-duty support gear designed for maximum training efficiency.' }
};

router.get('/products', (req, res) => res.json(products));
router.get('/testimonials', (req, res) => res.json(testimonials));
router.get('/themes', (req, res) => res.json(categoryThemes));
export default router;
